# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f26cc5b9c401f06b6a3b6cc6876572bcb21d71bcb58ad36b66417937446d9911c40ebabfe8b95da401abe16319400d504cf7d1d8b43ca36a93f838bef47482

test:
  secret_key_base: 68145fe18d1d0b59d8eefca5f8a45eea96d93270915214cdae51e083808089fb74a84f3f0ff9f06089700fe5465a491db679dbf65fce826b5b7329d099fad2d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
